# -*- coding: utf-8 -*-
"""massa_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dcmx5YXVu9oDArZvRoTwwoUv8EbvMxwu
"""

import random

#  lista com 250 números inteiros aleatórios entre 1 e 1000
numeros_aleatorios = [random.randint(1, 1000) for _ in range(250)]

# revertendo a ordem da lista
numeros_aleatorios.reverse()

# Imprimindo o resultado
print(numeros_aleatorios)

# Lista de nomes de 20 animais
animais = ["cachorro", "gato", "leão", "tigre", "urso", "elefante", "cavalo", "pato", "peixe",
           "papagaio", "aranha", "cobra", "arara", "coelho", "onça", "macaco", "tartaruga",
           "tatu-bola", "lhama", "pinguim"]

# Ordenando a lista em ordem crescente
animais.sort()


print("Lista ordenada:")
for animal in animais:
    print(animal)

# Salvando a lista em um arquivo CSV
with open("animais.csv", "w") as arquivo:
    for animal in animais:
        arquivo.write(animal + "\n")

print("\nLista salva no arquivo 'animais.csv'.")

!pip install names

import random
import names

random.seed(40)

# definir contidades
qtd_nomes_unicos = 3000
qtd_nomes_aleatorios = 10000000

# Gerando 3.000 nomes únicos
nomes_unicos = [names.get_full_name() for _ in range(qtd_nomes_unicos)]
print(f"Gerados {qtd_nomes_unicos} nomes únicos.")

# Gerando 10 milhões de nomes aleatórios baseados nos nomes únicos
nomes_aleatorios = [random.choice(nomes_unicos) for _ in range(qtd_nomes_aleatorios)]
print(f"Gerados {qtd_nomes_aleatorios} nomes aleatórios.")

# Salvando os nomes aleatórios em um arquivo
with open("nomes_aleatorios.txt", "w") as arquivo:
    for nome in nomes_aleatorios:
        arquivo.write(nome + "\n")

print("\nArquivo 'nomes_aleatorios.txt' criado com sucesso!")